version: "3.6"

services:

  mongo:
    image: mongo
    restart: always
    container_name: fipe-db
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db/
    networks:
      - fipe

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: .env
    networks:
      - fipe

  api:
    build:
      context: .
      dockerfile: ./.docker/app.dockerfile
    volumes:
      - .:/code
    container_name: fipe-api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - mongo
    networks:
      - fipe

  rabbitmq:
    image: rabbitmq:3.11.15-management-alpine
    container_name: fipe-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/fipe/rabbitmq'
    networks:
      - fipe

  worker:
    build:
      context: .
      dockerfile: ./.docker/worker.dockerfile
    container_name: worker-fipe
    env_file: .env
    depends_on:
      - api
    volumes:
      - .:/app
    networks:
      - fipe

volumes:
  mongo_data:

  rabbitmq_data:
    driver: local

networks:
  fipe:
    name: fipe